---
# For more information see
#  https://pre-commit.com/index.html#install
#  https://pre-commit.com/index.html#automatically-enabling-pre-commit-on-repositories
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-toml
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
#  - repo: "https://github.com/pre-commit/pygrep-hooks"
#    rev: v1.9.0
#    hooks:
#      - id: python-check-blanket-noqa
#      - id: python-check-blanket-type-ignore
#      - id: python-use-type-annotations
#  - repo: "https://github.com/pycqa/isort"
#    rev: 5.10.1
#    hooks:
#      - id: isort
#  - repo: "https://github.com/psf/black"
#    rev: 22.1.0
#    hooks:
#      - id: black
#  - repo: "https://github.com/pre-commit/mirrors-prettier"
#    rev: v2.5.1
#    hooks:
#      - id: prettier
#        exclude_types:
#          - "python"
#        additional_dependencies:
#          - "prettier"
#          - "prettier-plugin-toml@0.3.1"
#  - repo: "https://github.com/asottile/pyupgrade"
#    rev: v2.31.0
#    hooks:
#      - id: pyupgrade
#        args:
#          - "--py36-plus"
  - repo: "https://github.com/fsfe/reuse-tool"
    rev: v0.14.0
    hooks:
      - id: reuse
        additional_dependencies:
          - python-debian==0.1.40
#  jsonnetfmt requires golang 1.11+ and git 2.0, uncomment when we are compatible
#  - repo: https://github.com/google/go-jsonnet.git
#    rev: 2f2f6d664f06d064c4b3525ea34a789c1ac95cda
#    hooks:
#      - id: jsonnet-format
#        language_version: "1.11"
#        exclude: "empty.*|invalid.jsonnet"
#        args:
#          - "--in-place"
#          - "--string-style"
#          - "d"
#          - "--comment-style"
#          - "s"
#  sort-all requires python 3.8+, uncomment when we are compatible
#  - repo: "https://github.com/aio-libs/sort-all"
#    rev: v1.1.0
#    hooks:
#      - id: sort-all
#        language_version: "3.8"
